<?php $__env->startSection('content'); ?> <?php $__env->startComponent('juzaweb::components.form_resource', [
        'model' => $model,
    ]); ?><div class="row"><div class="col-md-8"> <?php echo e(Field::text($model, 'title', [
                    'required' => true,
                    'class' => empty($model->slug) ? 'generate-slug' : '',
                ])); ?><div class="options multi" id="dynamic_field" <?php if( $model->question_type=='3' || $model->question_type=='4' ): ?> style="display: none;" <?php endif; ?> > <?php if($model->options): ?> <?php
                         $options = json_decode($model->options);
                         $options = (array) $options;
                         $total_opt=count($options);
                      ?> <?php $__currentLoopData = $options; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=> $option): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div id="row<?php echo e($k); ?>" class="row"><div class="form-group col-sm-10 "><label class="control-label mb-10 text-left">Option <?php echo e($k+1); ?></label> <input type="text" id="input-file-max-fs<?php echo e($k); ?>" name="options[]" class="form-control" value="<?php echo e($option); ?>"></div> <?php if($k==0): ?> <?php elseif($k==1): ?><div class="form-group col-sm-2 "><button type="button" name="add" id="add" class="btn btn-success" style="margin-top:30px;">Add More</button></div> <?php elseif($k>1): ?><div class="form-group col-sm-2 "><button type="button" name="remove" id="<?php echo e($k); ?>" class="btn btn-danger btn_remove" style="margin-top:30px;">Remove</button></div> <?php endif; ?></div> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php else: ?><div class="row"><div class="form-group col-sm-10 "><label class="control-label mb-10 text-left">Option 1</label> <input type="text" id="input-file-max-fs" name="options[]" value="" class="form-control"></div><div class="form-group col-sm-2 "></div></div><div class="row"><div class="form-group col-sm-10 "><label class="control-label mb-10 text-left">Option 2</label> <input type="text" id="input-file-max-fs" name="options[]" value="" class="form-control"></div><div class="form-group col-sm-2 "><button type="button" name="add" id="add" class="btn btn-success" style="margin-top:30px;">Add More</button></div></div> <?php endif; ?></div> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('post_type.'. $postType .'.form.left'); ?></div><div class="col-md-4"><div class="form-group"><label class="control-label mb-10 text-left">Question Type</label> <select class="form-control" name="question_type" id="question_type"><option value="1" <?php if( $model->question_type=='1'): ?> selected="selected" <?php endif; ?>>Multiple choice(Single)</option><option value="2" <?php if( $model->question_type=='2'): ?> selected="selected" <?php endif; ?>>Multiple choice(Multiple)</option><option value="3" <?php if( $model->question_type=='3'): ?> selected="selected" <?php endif; ?>>True/False</option><option value="4" <?php if( $model->question_type=='4'): ?> selected="selected" <?php endif; ?>>Text field</option></select></div> <?php echo e(Field::select($model, 'status', [
                    'options' => $model->getStatuses()
                ])); ?> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('post_type.'. $postType .'.form.right', $model); ?></div></div> <?php echo $__env->renderComponent(); ?><script type="text/javascript">$(document).ready(function(){$('#question_type').on('change',function(){if(this.value==1||this.value==2){$('.multi').css('display','block');}else{$('.multi').css('display','none');}});var i=2;$('#add').click(function(){i++;$('#dynamic_field').append('<div class="row" id="row'+i+'"><div class="form-group col-sm-10 "><label class="control-label mb-10 text-left">Option '+i+'</label><input type="text" id="input-file-max-fs" name="options[]" class="form-control" /></div><div class="form-group col-sm-2 "><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove" style="margin-top:30px;">Remove</button></div></div>');});$(document).on('click','.btn_remove',function(){var button_id=$(this).attr("id");$('#row'+button_id+'').remove();});$('.datetimepicker').datetimepicker({format:'LT',useCurrent:false,icons:{time:"fa fa-clock-o",date:"fa fa-calendar",up:"fa fa-arrow-up",down:"fa fa-arrow-down"},});});</script><?php $__env->stopSection(); ?> <?php echo $__env->make('juzaweb::layouts.backend', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\wamp64\www\github\CreatePhoto\plugins/sbhadra/survey/src/resources/views/backend/question/form.blade.php ENDPATH**/ ?>