<?php $__env->startSection('content'); ?> <?php $__env->startComponent('juzaweb::components.form_resource', [
        'action' => $model->id ?
            route('admin.users.update', [$model->id]) :
            route('admin.users.store'),
        'method' => $model->id ? 'put' : 'post'
    ]); ?><div class="row"><div class="col-md-8"><div class="form-group"><label class="col-form-label" for="name"><?php echo app('translator')->get('juzaweb::app.name'); ?></label> <input type="text" name="name" class="form-control" id="name" value="<?php echo e($model->name); ?>" autocomplete="off" required></div><div class="form-group"><label class="col-form-label" for="email"><?php echo app('translator')->get('juzaweb::app.email'); ?></label> <input type="text" class="form-control" id="email" value="<?php echo e($model->email); ?>" autocomplete="off" <?php if($model->id): ?> disabled <?php else: ?> name="email" required <?php endif; ?>></div><div class="form-group"><label class="col-form-label" for="is_admin"><?php echo app('translator')->get('juzaweb::app.permission'); ?></label> <select name="is_admin" id="is_admin" class="form-control" required><option value="0" <?php if($model->is_admin == 0): ?> selected <?php endif; ?>><?php echo app('translator')->get('juzaweb::app.user'); ?></option><option value="1" <?php if($model->is_admin == 1): ?> selected <?php endif; ?>><?php echo app('translator')->get('juzaweb::app.admin'); ?></option></select></div><div class="form-group"><label class="col-form-label" for="status"><?php echo app('translator')->get('juzaweb::app.status'); ?></label> <select name="status" id="status" class="form-control" required> <?php $__currentLoopData = $allStatus; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $key => $name): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($key); ?>" <?php if($model->status == $key): ?> selected <?php endif; ?>><?php echo e($name); ?></option> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> </select></div><hr><div class="form-group"><label class="col-form-label" for="password"><?php echo app('translator')->get('juzaweb::app.password'); ?></label> <input type="password" name="password" class="form-control" id="password" autocomplete="off" <?php if(empty($model->id)): ?> required <?php endif; ?>></div><div class="form-group"><label class="col-form-label" for="password_confirmation"><?php echo app('translator')->get('juzaweb::app.confirm_password'); ?></label> <input type="password" name="password_confirmation" class="form-control" id="password_confirmation" autocomplete="off" <?php if(empty($model->id)): ?> required <?php endif; ?>></div></div><div class="col-md-4"><?php $__env->startComponent('juzaweb::components.form_image', [
                    'label' => trans('juzaweb::app.avatar'),
                    'name' => 'avatar',
                    'value' => $model->avatar
                ]); ?> <?php echo $__env->renderComponent(); ?></div></div><input type="hidden" name="id" value="<?php echo e($model->id); ?>"> <?php echo $__env->renderComponent(); ?> <?php $__env->stopSection(); ?> <?php echo $__env->make('juzaweb::layouts.backend', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\wamp64\www\github\CreatePhoto\vendor\juzaweb\cms\src\Providers/../resources/views/backend/user/form.blade.php ENDPATH**/ ?>