<?php $__env->startSection('content'); ?><script>var startDate='2022-01-01';var endDate='2046-12-31';var datesDisabled=["13-01-2022"];var daysOfWeekDisabled=[5,6]</script><form action="" method="get"><div class="row" ><div class="col-md-7"><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Select Package:</label><div class="col-sm-7 col-md-8"><select class="form-control form-control-lg" name="package_id"> <?php $__currentLoopData = $packages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $package): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($package->id); ?>"><?php echo e($package->title); ?></option> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> </select></div></div></div><div class="col-md-7"><div class="form-group"><input type="hidden" name="package_id" id="package_id" value="<?php echo e($post->id); ?>"><input class="form-control" id="date" name="date" placeholder="MM/DD/YYY" type="text" disabled /><div id="bookingdate"></div></div></div></div></form><div class="row" style="display:none"> <?php $__env->startComponent('juzaweb::components.form_resource', [
        'model' => $model,
    ]); ?><div class="col-md-8"><section><div class="container"><div class="row"><div class="col-12"><h2 class="shoots-Head2">Personal Information</h2></div><div class="col-md-8 col-sm-10"> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('admin.reservation.data'); ?> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('admin.reservation.time'); ?> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('admin.reservation.services'); ?><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Customer Name:</label><div class="col-sm-7 col-md-8"><input type="text" class="form-control form-control-lg" id="customer_name" name="customer_name" required ></div></div><div class="form-group row" style="display:none"><label for="" class="col-sm-5 col-md-4 col-form-label">Customer Email:</label><div class="col-sm-7 col-md-8"><input type="email" class="form-control form-control-lg" id="customer_email" name="customer_email" value="Hello@myshootskw.com" required></div></div><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Mobile Number:</label><div class="col-sm-7 col-md-8"><input type="text" class="form-control form-control-lg" id="mobile_number" name="mobile_number" required></div></div><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Baby Name:</label><div class="col-sm-7 col-md-8"><input type="text" class="form-control form-control-lg" id="baby_name" name="baby_name"></div></div><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Baby Age:</label><div class="col-sm-7 col-md-8"><input type="text" class="form-control form-control-lg" id="baby_age" name="baby_age"></div></div><div class="form-group row"><label for="" class="col-sm-5 col-md-4 col-form-label">Instructions:</label><div class="col-sm-7 col-md-8"><textarea name="instructions" id="instructions" class="form-control form-control-lg"  rows="4" placeholder=""></textarea></div></div> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('admin.reservation.fields'); ?>;</div></div></div></section> <?php app(\Juzaweb\Contracts\EventyContract::class)->action('post_type.'. $postType .'.form.left'); ?></div><div class="col-md-4"><?php app(\Juzaweb\Contracts\EventyContract::class)->action('post_type.'. $postType .'.form.right', $model); ?></div> <?php echo $__env->renderComponent(); ?></div><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/><style>.datepicker-inline{
            width: 100%;
            }
            .datepicker table {
            margin: 0;
            
            width: 100%;
        }</style><?php app(\Juzaweb\Contracts\EventyContract::class)->action('admin.calendar.hooks'); ?><script>$(document).ready(function(){var date_input=$('#bookingdate');var container=$('.bootstrap-iso form').length>0?$('.bootstrap-iso form').parent():"body";var options={format:"dd-mm-yyyy",inline:true,sideBySide:true,container:container,todayHighlight:true,daysOfWeekDisabled:daysOfWeekDisabled,datesDisabled:datesDisabled,autoclose:true,startDate:new Date(startDate),endDate:new Date(endDate),icons:{time:"fa fa-clock-o",date:"fa fa-calendar",up:"fa fa-arrow-up",down:"fa fa-arrow-down"},};date_input.datepicker(options).on('changeDate',showTestDate);function showTestDate(){var value=$('#bookingdate').datepicker('getFormattedDate');$("#date").val(value);}})
function truncateDate(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate());}
$(document).ready(function(){$('#booknow').click(function(){var date=$("#date").val();var package_id=$("#package_id").val();if(date!=""){window.location.href="<?php echo e(url('/reservations')); ?>?id="+package_id+"&date="+date;}else{alert("Please select date!");return false;}});})</script><?php $__env->stopSection(); ?> <?php echo $__env->make('juzaweb::layouts.backend', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\wamp64\www\github\CreatePhoto\plugins/sbhadra/photography/src/resources/views/backend/booking/create.blade.php ENDPATH**/ ?>